---

inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/master/.rubocop.yml
  - https://raw.githubusercontent.com/decidim/decidim/master/.rubocop_rails.yml

Naming/FileName:
  Exclude:
    - lib/generators/decidim/census_connector/install/templates/config/initializers/decidim-census_connector.rb
